# Generated by Django 4.2.6 on 2023-10-24 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_add', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('', 'не указано'), ('1A', '1a'), ('1B', '1б'), ('2А', '2а'), ('2В', '2б'), ('3А', '3а'), ('3В', '3б')], max_length=2)),
                ('spring', models.CharField(choices=[('', 'не указано'), ('1A', '1a'), ('1B', '1б'), ('2А', '2а'), ('2В', '2б'), ('3А', '3а'), ('3В', '3б')], max_length=2)),
                ('summer', models.CharField(choices=[('', 'не указано'), ('1A', '1a'), ('1B', '1б'), ('2А', '2а'), ('2В', '2б'), ('3А', '3а'), ('3В', '3б')], max_length=2)),
                ('autumn', models.CharField(choices=[('', 'не указано'), ('1A', '1a'), ('1B', '1б'), ('2А', '2а'), ('2В', '2б'), ('3А', '3а'), ('3В', '3б')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='pereval_added',
            name='level',
        ),
        migrations.AddField(
            model_name='pereval_added',
            name='images',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pereval_add.pereval_image'),
        ),
        migrations.AddField(
            model_name='pereval_added',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('pending', 'на модерации'), ('accepted', 'принят'), ('rejected', 'не принят')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='coords',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coords',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coords',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pereval_added',
            name='beautyTitle',
            field=models.CharField(choices=[('poss', 'перевал'), ('gorge', 'ущелье'), ('plateau', 'плато')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.AddField(
            model_name='pereval_added',
            name='season',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pereval_add.season'),
        ),
    ]
